const fs = require('node:fs')
const path = require('node:path')
const { spawnSync } = require('node:child_process')
const root = path.resolve(__dirname, '..')
const mini = path.join(root, 'miniprogram')
const fontDir = path.join(mini, 'assets/fonts')
const sourceDir = path.join(__dirname, 'assets/remixicon')
const sourceCss = path.join(sourceDir, 'source.wxss')
const sourceFont = path.join(sourceDir, 'source.woff2')
const outputCss = path.join(fontDir, 'remixicon.wxss')
const outputFont = path.join(fontDir, 'remixicon.woff2')

function files(directory) {
  return fs.readdirSync(directory, { withFileTypes: true }).flatMap(entry => {
    const file = path.join(directory, entry.name)
    return entry.isDirectory() ? files(file) : [file]
  })
}
function usedIcons(mapping) {
  const used = new Set(['ri-arrow-down-s-line', 'ri-arrow-right-s-line'])
  const missing = new Map()
  const sizes = /^ri-(lg|xl|xxs|xs|sm|fw|\d+x)$/
  for (const file of files(mini).filter(file => /\.(js|wxml|wxss|json)$/.test(file) && !file.startsWith(fontDir))) {
    let source = fs.readFileSync(file, 'utf8')
    source = source.replace("ri-arrow-{{node.expanded ? 'down' : 'right'}}-s-line", 'ri-arrow-down-s-line ri-arrow-right-s-line')
    if (/\bri-[\w-]*(\{\{|\$\{)/.test(source)) throw new Error(`动态图标需要加入显式映射: ${path.relative(root, file)}`)
    for (const name of source.match(/\bri-[a-z0-9]+(?:-[a-z0-9]+)*/g) || []) {
      if (sizes.test(name)) continue
      if (!mapping.has(name)) missing.set(name, path.relative(root, file))
      else used.add(name)
    }
  }
  if (missing.size) throw new Error([...missing].map(([name, file]) => `未定义图标 ${name}: ${file}`).join('\n'))
  return [...used].sort()
}

function optimize(check = false) {
  if (!fs.existsSync(sourceCss) || !fs.existsSync(sourceFont)) {
    if (check) throw new Error('缺少完整字体源文件')
    const original = fs.readFileSync(outputCss, 'utf8')
    if ((original.match(/:before/g) || []).length < 1000) throw new Error('无法从裁剪字体恢复完整源文件')
    fs.mkdirSync(sourceDir, { recursive: true })
    fs.writeFileSync(sourceCss, original.replace(/@font-face\s*\{[^}]*\}/, ''))
    fs.copyFileSync(outputFont, sourceFont)
  }
  const source = fs.readFileSync(sourceCss, 'utf8')
  const pattern = /^\.([\w-]+):before\s*\{\s*content:\s*"\\([0-9a-f]+)";\s*\}/gm
  const mapping = new Map([...source.matchAll(pattern)].map(match => [match[1], { rule: match[0], code: match[2] }]))
  // Older page names are aliases; Remix v4.9.1 does not define these names.
  const aliases = { 'ri-shield-heart-line': 'ri-shield-check-line', 'ri-shield-heart-fill': 'ri-shield-check-fill',
    'ri-shield-smile-line': 'ri-shield-user-line', 'ri-shield-alert-fill': 'ri-shield-cross-fill',
    'ri-paw-print-line': 'ri-footprint-line', 'ri-paw-print-fill': 'ri-footprint-fill',
    'ri-list-check-3-line': 'ri-list-check-3', 'ri-mail-gift-fill': 'ri-gift-fill',
    'ri-mail-gift-line': 'ri-gift-line', 'ri-font-size-line': 'ri-font-size' }
  for (const [alias, name] of Object.entries(aliases)) {
    const glyph = mapping.get(name)
    if (!glyph) throw new Error(`别名源图标不存在: ${name}`)
    mapping.set(alias, { code: glyph.code, rule: glyph.rule.replace(name, alias) })
  }
  const names = usedIcons(mapping)
  if (check) {
    const css = fs.readFileSync(outputCss, 'utf8')
    for (const name of names) if (!css.includes(mapping.get(name).rule)) throw new Error(`需重新生成字体: ${name}`)
    const embedded = css.match(/base64,([A-Za-z0-9+/=]+)/)
    if (!embedded || !Buffer.from(embedded[1], 'base64').equals(fs.readFileSync(outputFont))) throw new Error('字体与嵌入文件不一致')
    return { icons: names.length, cssBytes: fs.statSync(outputCss).size, fontBytes: fs.statSync(outputFont).size }
  }
  const result = spawnSync(process.env.ICON_PYTHON || 'python', ['-m', 'fontTools.subset', sourceFont,
    `--output-file=${outputFont}`, '--flavor=woff2', `--unicodes=${names.map(name => `U+${mapping.get(name).code}`).join(',')}`], { encoding: 'utf8' })
  if (result.error || result.status !== 0) throw new Error(result.error?.message || result.stderr || '请安装 fonttools 和 brotli')
  const data = fs.readFileSync(outputFont).toString('base64')
  const base = source.slice(0, source.search(/^\.ri-[\w-]+:before/m)).trim()
  const css = `/* Generated by scripts/optimize-icons.js; source stays outside the mini program. */\n@font-face { font-family: 'remixicon'; src: url('data:font/woff2;base64,${data}') format('woff2'); font-weight: normal; font-style: normal; }\n${base}\n${names.map(name => mapping.get(name).rule).join('\n')}\n`
  fs.writeFileSync(outputCss, css)
  return optimize(true)
}

if (require.main === module) {
  try { console.log(JSON.stringify(optimize(process.argv.includes('--check')))) }
  catch (error) { console.error(error.message); process.exitCode = 1 }
}
module.exports = { optimize }
